/* The following code was generated by JFlex 1.6.1 */

package daikon.parser;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/Users/giovanni/repository/java-xal/daikon-instrumentation/grammar/calc.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\54\1\1\2\7\1\2\22\0\1\43\1\26\1\3\5\0"+
    "\1\10\1\14\2\0\1\24\1\4\1\5\1\0\12\6\1\15\1\0"+
    "\1\27\1\22\1\25\2\0\1\34\1\37\1\32\1\4\1\16\3\4"+
    "\1\20\1\40\1\4\1\33\1\4\1\30\1\36\2\4\1\31\1\35"+
    "\1\21\3\4\1\17\13\4\1\13\1\42\1\44\1\53\1\4\1\50"+
    "\2\4\1\45\1\11\1\41\1\12\2\4\1\52\1\47\1\46\5\4"+
    "\1\51\1\23\1\0\1\23\7\0\1\7\32\0\1\7\u15df\0\1\7"+
    "\u097f\0\13\7\35\0\2\7\5\0\1\7\57\0\1\7\u0fa0\0\1\7"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\2\3\1\4\1\3\2\1"+
    "\1\5\1\6\1\1\1\7\1\3\1\10\2\3\2\0"+
    "\2\3\1\0\1\11\1\12\1\13\1\14\2\3\1\0"+
    "\2\3\2\0\1\15\2\3\2\0\1\16\4\0\1\3"+
    "\1\17\7\0\1\3\1\0\1\20\5\0\1\3\1\0"+
    "\1\21\4\0\1\3\1\22\1\23\1\24\2\0\1\25"+
    "\1\26\102\0\1\27";

  private static int [] zzUnpackAction() {
    int [] result = new int[144];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\55\0\132\0\207\0\264\0\341\0\55"+
    "\0\u010e\0\u013b\0\u0168\0\55\0\u0195\0\u01c2\0\u01ef\0\u021c"+
    "\0\u0249\0\u0276\0\55\0\u02a3\0\u02d0\0\u02fd\0\u032a\0\u0357"+
    "\0\u0384\0\55\0\55\0\55\0\u03b1\0\u03de\0\u040b\0\u0438"+
    "\0\u0465\0\u0492\0\u04bf\0\55\0\u04ec\0\u0519\0\u0546\0\u0573"+
    "\0\264\0\u05a0\0\u05cd\0\u05fa\0\u0627\0\u0654\0\264\0\u0681"+
    "\0\u06ae\0\u06db\0\u0708\0\u0735\0\u0762\0\u078f\0\u07bc\0\u07e9"+
    "\0\55\0\u0816\0\u0843\0\u0870\0\u089d\0\u08ca\0\u08f7\0\u0924"+
    "\0\u0951\0\u097e\0\u09ab\0\u09d8\0\u0a05\0\u0a32\0\55\0\55"+
    "\0\55\0\u0a5f\0\u0a8c\0\264\0\55\0\u0ab9\0\u0ae6\0\u0b13"+
    "\0\u0b40\0\u0b6d\0\u0b9a\0\u0bc7\0\u0bf4\0\u0c21\0\u0c4e\0\u0c7b"+
    "\0\u0ca8\0\u0cd5\0\u0d02\0\u0d2f\0\u0d5c\0\u0d89\0\u0db6\0\u0de3"+
    "\0\u0e10\0\u0e3d\0\u0e6a\0\u0e97\0\u0ec4\0\u0ef1\0\u0f1e\0\u0f4b"+
    "\0\u0f78\0\u0fa5\0\u0fd2\0\u0fff\0\u102c\0\u1059\0\u1086\0\u10b3"+
    "\0\u10e0\0\u110d\0\u113a\0\u1167\0\u1194\0\u11c1\0\u11ee\0\u121b"+
    "\0\u1248\0\u1275\0\u12a2\0\u12cf\0\u12fc\0\u1329\0\u1356\0\u1383"+
    "\0\u13b0\0\u13dd\0\u140a\0\u1437\0\u1464\0\u1491\0\u14be\0\u14eb"+
    "\0\u1518\0\u1545\0\u1572\0\u159f\0\u15cc\0\u15f9\0\u1626\0\55";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[144];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\2\1\7\1\2"+
    "\1\10\1\6\1\11\1\6\1\10\1\12\4\6\1\13"+
    "\1\10\1\14\1\15\1\16\1\17\12\6\1\20\1\21"+
    "\3\6\1\22\4\6\1\21\56\0\1\3\57\0\1\6"+
    "\1\0\1\6\2\0\3\6\2\0\4\6\6\0\13\6"+
    "\1\0\10\6\4\0\1\23\3\6\2\0\3\6\2\0"+
    "\4\6\6\0\13\6\1\0\10\6\2\0\2\24\1\23"+
    "\2\6\1\7\1\24\1\25\3\6\2\0\4\6\6\0"+
    "\13\6\1\24\10\6\1\24\3\0\1\23\3\6\2\0"+
    "\3\6\2\0\4\6\6\0\11\6\1\26\1\6\1\0"+
    "\6\6\1\27\1\6\16\0\1\30\61\0\1\31\54\0"+
    "\1\32\54\0\1\33\54\0\1\34\35\0\1\23\3\6"+
    "\2\0\3\6\2\0\4\6\6\0\13\6\1\0\1\6"+
    "\1\35\6\6\44\0\1\21\10\0\1\21\3\0\1\23"+
    "\3\6\2\0\3\6\2\0\4\6\6\0\13\6\1\0"+
    "\4\6\1\36\3\6\2\0\2\24\4\0\1\24\1\25"+
    "\32\0\1\24\10\0\1\24\11\0\1\37\46\0\1\23"+
    "\3\6\2\0\3\6\2\0\4\6\6\0\12\6\1\40"+
    "\1\0\10\6\4\0\1\23\3\6\2\0\3\6\2\0"+
    "\4\6\6\0\13\6\1\0\4\6\1\41\3\6\16\0"+
    "\1\42\61\0\1\43\2\0\1\44\32\0\1\23\3\6"+
    "\2\0\3\6\2\0\4\6\6\0\12\6\1\45\1\0"+
    "\10\6\4\0\1\23\3\6\2\0\3\6\2\0\4\6"+
    "\6\0\13\6\1\0\5\6\1\46\2\6\13\0\1\47"+
    "\45\0\1\23\3\6\2\0\3\6\2\0\4\6\6\0"+
    "\13\6\1\50\10\6\4\0\1\23\3\6\2\0\3\6"+
    "\2\0\4\6\6\0\13\6\1\0\7\6\1\51\17\0"+
    "\1\52\13\0\1\53\3\0\1\54\40\0\1\55\35\0"+
    "\1\23\3\6\2\0\1\56\2\6\2\0\4\6\6\0"+
    "\13\6\1\0\10\6\4\0\1\23\3\6\2\0\3\6"+
    "\2\0\4\6\6\0\12\6\1\57\1\0\10\6\14\0"+
    "\1\60\53\0\1\61\61\0\1\62\10\0\1\63\57\0"+
    "\1\64\60\0\1\65\37\0\1\66\35\0\1\23\3\6"+
    "\2\0\3\6\2\0\4\6\6\0\12\6\1\67\1\0"+
    "\10\6\2\0\2\70\4\0\1\70\33\0\1\70\10\0"+
    "\1\70\44\0\1\71\30\0\1\72\55\0\1\73\67\0"+
    "\1\74\60\0\1\75\36\0\1\76\35\0\1\23\3\6"+
    "\2\0\3\6\2\0\4\6\6\0\11\6\1\77\1\6"+
    "\1\0\10\6\2\0\2\70\3\0\1\100\1\70\33\0"+
    "\1\70\10\0\1\70\21\0\1\101\51\0\1\102\73\0"+
    "\1\103\35\0\1\104\60\0\1\105\35\0\1\23\3\6"+
    "\2\0\3\6\2\0\4\6\6\0\13\6\1\0\2\6"+
    "\1\106\5\6\7\0\1\100\5\0\1\107\46\0\1\101"+
    "\77\0\1\110\60\0\1\111\51\0\1\112\44\0\1\113"+
    "\35\0\1\23\3\6\2\0\3\6\2\0\4\6\6\0"+
    "\13\6\1\0\3\6\1\114\4\6\22\0\1\115\55\0"+
    "\1\116\54\0\1\117\54\0\1\120\54\0\1\121\54\0"+
    "\1\122\54\0\1\123\54\0\1\124\54\0\1\125\54\0"+
    "\1\126\54\0\1\127\54\0\1\130\54\0\1\131\54\0"+
    "\1\132\54\0\1\133\54\0\1\134\54\0\1\135\54\0"+
    "\1\136\54\0\1\137\54\0\1\140\54\0\1\141\54\0"+
    "\1\142\54\0\1\143\54\0\1\144\54\0\1\145\54\0"+
    "\1\146\54\0\1\147\54\0\1\150\54\0\1\151\54\0"+
    "\1\152\54\0\1\153\54\0\1\154\54\0\1\155\54\0"+
    "\1\156\54\0\1\157\54\0\1\160\54\0\1\161\54\0"+
    "\1\162\54\0\1\163\54\0\1\164\54\0\1\165\54\0"+
    "\1\166\54\0\1\167\54\0\1\170\54\0\1\171\54\0"+
    "\1\172\54\0\1\173\54\0\1\174\54\0\1\175\54\0"+
    "\1\176\54\0\1\177\54\0\1\200\54\0\1\201\54\0"+
    "\1\202\54\0\1\203\54\0\1\204\54\0\1\205\54\0"+
    "\1\206\54\0\1\207\54\0\1\210\54\0\1\211\54\0"+
    "\1\212\54\0\1\213\54\0\1\214\54\0\1\215\54\0"+
    "\1\216\54\0\1\217\54\0\1\220\32\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5715];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\4\1\1\11\3\1\1\11\6\1\1\11"+
    "\2\0\2\1\1\0\1\1\3\11\2\1\1\0\2\1"+
    "\2\0\1\11\2\1\2\0\1\1\4\0\2\1\7\0"+
    "\1\1\1\0\1\11\5\0\1\1\1\0\1\1\4\0"+
    "\1\1\3\11\2\0\1\1\1\11\102\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[144];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  private Parser yyparser;

  public int line = 1;
  public boolean debug = true;

  public Yylex(java.io.Reader r, Parser yyparser) {
    this(r);
    this.yyparser = yyparser;
  }

  public String getBuffer(){
      return new String(this.zzBuffer, this.zzCurrentPos, this.zzEndRead-this.zzStartRead);
  }
  public String getBuffer(int lookaheadLines){
      if(lookaheadLines < 1)
        lookaheadLines = 1;
      int start = zzCurrentPos;
      while(lookaheadLines != 0){
        if(this.zzBuffer[start] == '\n')
          lookaheadLines--;
        start++;
        if(this.zzBuffer.length <= start)
          lookaheadLines = 0;
      }
      return new String(this.zzBuffer, this.zzCurrentPos, start-this.zzCurrentPos);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 194) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return 0; }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("[" + line + "] Error: unexpected character '"+yytext()+"'");
            }
          case 24: break;
          case 2: 
            { line++;
            }
          case 25: break;
          case 3: 
            { yyparser.yylval = new ParserVal(yytext());
        return Parser.TEXT;
            }
          case 26: break;
          case 4: 
            { return (int) yycharat(0);
            }
          case 27: break;
          case 5: 
            { return Parser.COMMA;
            }
          case 28: break;
          case 6: 
            { return Parser.G;
            }
          case 29: break;
          case 7: 
            { return Parser.L;
            }
          case 30: break;
          case 8: 
            { 
            }
          case 31: break;
          case 9: 
            { return Parser.EQUAL;
            }
          case 32: break;
          case 10: 
            { return Parser.GEQ;
            }
          case 33: break;
          case 11: 
            { return Parser.NEQUAL;
            }
          case 34: break;
          case 12: 
            { return Parser.LEQ;
            }
          case 35: break;
          case 13: 
            { return Parser.IF;
            }
          case 36: break;
          case 14: 
            { return Parser.ORIG;
            }
          case 37: break;
          case 15: 
            { return Parser.SIZE;
            }
          case 38: break;
          case 16: 
            { return Parser.ONEOF;
            }
          case 39: break;
          case 17: 
            { yyparser.yylval = new ParserVal(yytext());return Parser.EXIT;
            }
          case 40: break;
          case 18: 
            { yyparser.yylval = new ParserVal(yytext());
        return Parser.MOD;
            }
          case 41: break;
          case 19: 
            { return Parser.ENTER;
            }
          case 42: break;
          case 20: 
            { return Parser.CLASS;
            }
          case 43: break;
          case 21: 
            { return Parser.ELEMS;
            }
          case 44: break;
          case 22: 
            { return Parser.OBJECT;
            }
          case 45: break;
          case 23: 
            { return Parser.SEP;
            }
          case 46: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
